export const CURRENCIES = [
  // ── Popular ──────────────────────────────────────────────────────────────────
  { code: 'USD', name: 'US Dollar',                        symbol: '$'    },
  { code: 'EUR', name: 'Euro',                             symbol: '€'    },
  { code: 'GBP', name: 'British Pound',                    symbol: '£'    },
  { code: 'AED', name: 'UAE Dirham',                       symbol: 'د.إ'  },
  { code: 'SAR', name: 'Saudi Riyal',                      symbol: '﷼'    },
  { code: 'INR', name: 'Indian Rupee',                     symbol: '₹'    },
  { code: 'CAD', name: 'Canadian Dollar',                  symbol: 'CA$'  },
  { code: 'AUD', name: 'Australian Dollar',                symbol: 'A$'   },
  { code: 'JPY', name: 'Japanese Yen',                     symbol: '¥'    },
  { code: 'CHF', name: 'Swiss Franc',                      symbol: 'Fr'   },
  { code: 'CNY', name: 'Chinese Yuan',                     symbol: '¥'    },
  { code: 'SGD', name: 'Singapore Dollar',                 symbol: 'S$'   },
  // ── A ────────────────────────────────────────────────────────────────────────
  { code: 'AFN', name: 'Afghan Afghani',                   symbol: '؋'    },
  { code: 'ALL', name: 'Albanian Lek',                     symbol: 'L'    },
  { code: 'DZD', name: 'Algerian Dinar',                   symbol: 'دج'   },
  { code: 'AOA', name: 'Angolan Kwanza',                   symbol: 'Kz'   },
  { code: 'ARS', name: 'Argentine Peso',                   symbol: '$'    },
  { code: 'AMD', name: 'Armenian Dram',                    symbol: '֏'    },
  { code: 'AWG', name: 'Aruban Florin',                    symbol: 'ƒ'    },
  { code: 'AZN', name: 'Azerbaijani Manat',                symbol: '₼'    },
  // ── B ────────────────────────────────────────────────────────────────────────
  { code: 'BSD', name: 'Bahamian Dollar',                  symbol: 'B$'   },
  { code: 'BHD', name: 'Bahraini Dinar',                   symbol: 'BD'   },
  { code: 'BDT', name: 'Bangladeshi Taka',                 symbol: '৳'    },
  { code: 'BBD', name: 'Barbadian Dollar',                 symbol: 'Bds$' },
  { code: 'BYN', name: 'Belarusian Ruble',                 symbol: 'Br'   },
  { code: 'BZD', name: 'Belize Dollar',                    symbol: 'BZ$'  },
  { code: 'BTN', name: 'Bhutanese Ngultrum',               symbol: 'Nu'   },
  { code: 'BOB', name: 'Bolivian Boliviano',               symbol: 'Bs'   },
  { code: 'BAM', name: 'Bosnia-Herzegovinian Mark',        symbol: 'KM'   },
  { code: 'BWP', name: 'Botswana Pula',                    symbol: 'P'    },
  { code: 'BRL', name: 'Brazilian Real',                   symbol: 'R$'   },
  { code: 'BND', name: 'Brunei Dollar',                    symbol: 'B$'   },
  { code: 'BGN', name: 'Bulgarian Lev',                    symbol: 'лв'   },
  { code: 'BIF', name: 'Burundian Franc',                  symbol: 'Fr'   },
  // ── C ────────────────────────────────────────────────────────────────────────
  { code: 'CVE', name: 'Cape Verdean Escudo',              symbol: '$'    },
  { code: 'KHR', name: 'Cambodian Riel',                   symbol: '៛'    },
  { code: 'XAF', name: 'Central African CFA Franc',        symbol: 'FCFA' },
  { code: 'KYD', name: 'Cayman Islands Dollar',            symbol: 'CI$'  },
  { code: 'CLP', name: 'Chilean Peso',                     symbol: '$'    },
  { code: 'COP', name: 'Colombian Peso',                   symbol: '$'    },
  { code: 'KMF', name: 'Comorian Franc',                   symbol: 'CF'   },
  { code: 'CDF', name: 'Congolese Franc',                  symbol: 'Fr'   },
  { code: 'CRC', name: 'Costa Rican Colón',                symbol: '₡'    },
  { code: 'CUP', name: 'Cuban Peso',                       symbol: '$'    },
  { code: 'CZK', name: 'Czech Koruna',                     symbol: 'Kč'   },
  // ── D ────────────────────────────────────────────────────────────────────────
  { code: 'DKK', name: 'Danish Krone',                     symbol: 'kr'   },
  { code: 'DJF', name: 'Djiboutian Franc',                 symbol: 'Fr'   },
  { code: 'DOP', name: 'Dominican Peso',                   symbol: 'RD$'  },
  // ── E ────────────────────────────────────────────────────────────────────────
  { code: 'XCD', name: 'East Caribbean Dollar',            symbol: 'EC$'  },
  { code: 'EGP', name: 'Egyptian Pound',                   symbol: 'E£'   },
  { code: 'ERN', name: 'Eritrean Nakfa',                   symbol: 'Nfk'  },
  { code: 'ETB', name: 'Ethiopian Birr',                   symbol: 'Br'   },
  // ── F ────────────────────────────────────────────────────────────────────────
  { code: 'FJD', name: 'Fijian Dollar',                    symbol: 'FJ$'  },
  { code: 'FKP', name: 'Falkland Islands Pound',           symbol: '£'    },
  // ── G ────────────────────────────────────────────────────────────────────────
  { code: 'GMD', name: 'Gambian Dalasi',                   symbol: 'D'    },
  { code: 'GEL', name: 'Georgian Lari',                    symbol: '₾'    },
  { code: 'GHS', name: 'Ghanaian Cedi',                    symbol: '₵'    },
  { code: 'GIP', name: 'Gibraltar Pound',                  symbol: '£'    },
  { code: 'GTQ', name: 'Guatemalan Quetzal',               symbol: 'Q'    },
  { code: 'GNF', name: 'Guinean Franc',                    symbol: 'Fr'   },
  { code: 'GYD', name: 'Guyanese Dollar',                  symbol: 'G$'   },
  // ── H ────────────────────────────────────────────────────────────────────────
  { code: 'HTG', name: 'Haitian Gourde',                   symbol: 'G'    },
  { code: 'HNL', name: 'Honduran Lempira',                 symbol: 'L'    },
  { code: 'HKD', name: 'Hong Kong Dollar',                 symbol: 'HK$'  },
  { code: 'HUF', name: 'Hungarian Forint',                 symbol: 'Ft'   },
  // ── I ────────────────────────────────────────────────────────────────────────
  { code: 'ISK', name: 'Icelandic Króna',                  symbol: 'kr'   },
  { code: 'IDR', name: 'Indonesian Rupiah',                symbol: 'Rp'   },
  { code: 'IRR', name: 'Iranian Rial',                     symbol: '﷼'    },
  { code: 'IQD', name: 'Iraqi Dinar',                      symbol: 'ع.د'  },
  { code: 'ILS', name: 'Israeli New Shekel',               symbol: '₪'    },
  // ── J ────────────────────────────────────────────────────────────────────────
  { code: 'JMD', name: 'Jamaican Dollar',                  symbol: 'J$'   },
  { code: 'JOD', name: 'Jordanian Dinar',                  symbol: 'JD'   },
  // ── K ────────────────────────────────────────────────────────────────────────
  { code: 'KZT', name: 'Kazakhstani Tenge',                symbol: '₸'    },
  { code: 'KES', name: 'Kenyan Shilling',                  symbol: 'KSh'  },
  { code: 'KPW', name: 'North Korean Won',                 symbol: '₩'    },
  { code: 'KRW', name: 'South Korean Won',                 symbol: '₩'    },
  { code: 'KWD', name: 'Kuwaiti Dinar',                    symbol: 'KD'   },
  { code: 'KGS', name: 'Kyrgyzstani Som',                  symbol: 'с'    },
  // ── L ────────────────────────────────────────────────────────────────────────
  { code: 'LAK', name: 'Lao Kip',                          symbol: '₭'    },
  { code: 'LBP', name: 'Lebanese Pound',                   symbol: 'ل.ل'  },
  { code: 'LSL', name: 'Lesotho Loti',                     symbol: 'L'    },
  { code: 'LRD', name: 'Liberian Dollar',                  symbol: 'L$'   },
  { code: 'LYD', name: 'Libyan Dinar',                     symbol: 'LD'   },
  // ── M ────────────────────────────────────────────────────────────────────────
  { code: 'MOP', name: 'Macanese Pataca',                  symbol: 'P'    },
  { code: 'MKD', name: 'Macedonian Denar',                 symbol: 'ден'  },
  { code: 'MGA', name: 'Malagasy Ariary',                  symbol: 'Ar'   },
  { code: 'MWK', name: 'Malawian Kwacha',                  symbol: 'MK'   },
  { code: 'MYR', name: 'Malaysian Ringgit',                symbol: 'RM'   },
  { code: 'MVR', name: 'Maldivian Rufiyaa',                symbol: 'Rf'   },
  { code: 'MRU', name: 'Mauritanian Ouguiya',              symbol: 'UM'   },
  { code: 'MUR', name: 'Mauritian Rupee',                  symbol: '₨'    },
  { code: 'MXN', name: 'Mexican Peso',                     symbol: '$'    },
  { code: 'MDL', name: 'Moldovan Leu',                     symbol: 'L'    },
  { code: 'MNT', name: 'Mongolian Tögrög',                 symbol: '₮'    },
  { code: 'MAD', name: 'Moroccan Dirham',                  symbol: 'MAD'  },
  { code: 'MZN', name: 'Mozambican Metical',               symbol: 'MT'   },
  { code: 'MMK', name: 'Myanmar Kyat',                     symbol: 'K'    },
  // ── N ────────────────────────────────────────────────────────────────────────
  { code: 'NAD', name: 'Namibian Dollar',                  symbol: 'N$'   },
  { code: 'NPR', name: 'Nepalese Rupee',                   symbol: '₨'    },
  { code: 'ANG', name: 'Netherlands Antillean Guilder',    symbol: 'ƒ'    },
  { code: 'NZD', name: 'New Zealand Dollar',               symbol: 'NZ$'  },
  { code: 'NIO', name: 'Nicaraguan Córdoba',               symbol: 'C$'   },
  { code: 'NGN', name: 'Nigerian Naira',                   symbol: '₦'    },
  { code: 'NOK', name: 'Norwegian Krone',                  symbol: 'kr'   },
  // ── O ────────────────────────────────────────────────────────────────────────
  { code: 'OMR', name: 'Omani Rial',                       symbol: 'ر.ع.' },
  // ── P ────────────────────────────────────────────────────────────────────────
  { code: 'PKR', name: 'Pakistani Rupee',                  symbol: '₨'    },
  { code: 'PAB', name: 'Panamanian Balboa',                symbol: 'B/.'  },
  { code: 'PGK', name: 'Papua New Guinean Kina',           symbol: 'K'    },
  { code: 'PYG', name: 'Paraguayan Guaraní',               symbol: '₲'    },
  { code: 'PEN', name: 'Peruvian Sol',                     symbol: 'S/'   },
  { code: 'PHP', name: 'Philippine Peso',                  symbol: '₱'    },
  { code: 'PLN', name: 'Polish Złoty',                     symbol: 'zł'   },
  // ── Q ────────────────────────────────────────────────────────────────────────
  { code: 'QAR', name: 'Qatari Riyal',                     symbol: 'ر.ق'  },
  // ── R ────────────────────────────────────────────────────────────────────────
  { code: 'RON', name: 'Romanian Leu',                     symbol: 'lei'  },
  { code: 'RUB', name: 'Russian Ruble',                    symbol: '₽'    },
  { code: 'RWF', name: 'Rwandan Franc',                    symbol: 'Fr'   },
  // ── S ────────────────────────────────────────────────────────────────────────
  { code: 'WST', name: 'Samoan Tālā',                      symbol: 'T'    },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra',        symbol: 'Db'   },
  { code: 'RSD', name: 'Serbian Dinar',                    symbol: 'din'  },
  { code: 'SCR', name: 'Seychellois Rupee',                symbol: '₨'    },
  { code: 'SLE', name: 'Sierra Leonean Leone',             symbol: 'Le'   },
  { code: 'SBD', name: 'Solomon Islands Dollar',           symbol: 'SI$'  },
  { code: 'SOS', name: 'Somali Shilling',                  symbol: 'Sh'   },
  { code: 'ZAR', name: 'South African Rand',               symbol: 'R'    },
  { code: 'SSP', name: 'South Sudanese Pound',             symbol: '£'    },
  { code: 'LKR', name: 'Sri Lankan Rupee',                 symbol: '₨'    },
  { code: 'SDG', name: 'Sudanese Pound',                   symbol: 'ج.س.' },
  { code: 'SRD', name: 'Surinamese Dollar',                symbol: 'SR$'  },
  { code: 'SZL', name: 'Swazi Lilangeni',                  symbol: 'L'    },
  { code: 'SEK', name: 'Swedish Krona',                    symbol: 'kr'   },
  { code: 'SYP', name: 'Syrian Pound',                     symbol: 'LS'   },
  // ── T ────────────────────────────────────────────────────────────────────────
  { code: 'TWD', name: 'New Taiwan Dollar',                symbol: 'NT$'  },
  { code: 'TJS', name: 'Tajikistani Somoni',               symbol: 'SM'   },
  { code: 'TZS', name: 'Tanzanian Shilling',               symbol: 'TSh'  },
  { code: 'THB', name: 'Thai Baht',                        symbol: '฿'    },
  { code: 'TOP', name: 'Tongan Paʻanga',                   symbol: 'T$'   },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar',         symbol: 'TT$'  },
  { code: 'TND', name: 'Tunisian Dinar',                   symbol: 'DT'   },
  { code: 'TRY', name: 'Turkish Lira',                     symbol: '₺'    },
  { code: 'TMT', name: 'Turkmenistani Manat',              symbol: 'T'    },
  // ── U ────────────────────────────────────────────────────────────────────────
  { code: 'UGX', name: 'Ugandan Shilling',                 symbol: 'USh'  },
  { code: 'UAH', name: 'Ukrainian Hryvnia',                symbol: '₴'    },
  { code: 'UYU', name: 'Uruguayan Peso',                   symbol: '$U'   },
  { code: 'UZS', name: 'Uzbekistani Som',                  symbol: 'сўм'  },
  // ── V ────────────────────────────────────────────────────────────────────────
  { code: 'VUV', name: 'Vanuatu Vatu',                     symbol: 'Vt'   },
  { code: 'VES', name: 'Venezuelan Bolívar',               symbol: 'Bs.S' },
  { code: 'VND', name: 'Vietnamese Đồng',                  symbol: '₫'    },
  // ── W ────────────────────────────────────────────────────────────────────────
  { code: 'XOF', name: 'West African CFA Franc',           symbol: 'CFA'  },
  // ── Y ────────────────────────────────────────────────────────────────────────
  { code: 'YER', name: 'Yemeni Rial',                      symbol: '﷼'    },
  // ── Z ────────────────────────────────────────────────────────────────────────
  { code: 'ZMW', name: 'Zambian Kwacha',                   symbol: 'ZK'   },
  { code: 'ZWL', name: 'Zimbabwean Dollar',                symbol: 'Z$'   },
];
